### ISSUE TITLE
容器未找到: Init failed! Maybe you should install `hyperf/pimple` first

### ISSUE THREAD

**Issue by nicolaslei** [yansongda/artful#20]
## PHP版本
8.2

我看hyperf/pimple依赖是在require_dev中

## 报错详情
Yansongda\Artful\Exception\ContainerNotFoundException: 容器未找到: Init failed! Maybe you should install `hyperf/pimple` first in /xxxx/vendor/yansongda/artful/src/Service/ContainerServiceProvider.php:99

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

**Comment by yansongda** [comment]
需要自行安装 hyperf/pimple 或者 illuminate/container

Pay 和 artful 的文档均有写

**Comment by nicolaslei** [comment]
> 需要自行安装 hyperf/pimple 或者 illuminate/container
> 
> Pay 和 artful 的文档均有写

好的，是我文档没看全，谢谢
